GET http://localhost:3000/api/inmuebles
###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": 3,
    "letra": "C",
    "extension": 100,
    "habitaciones": 3,
    "alquilado": true,
    "propietario": "Marcos",
    "email": "marcos@correo.com"
}

###
PUT http://localhost:3000/api/inmuebles/646b722ecdcb20a890b80c87
Content-Type: application/json

{
    "alquilado": false,
    "email": "marcos2@correo.com"
}
###
DELETE http://localhost:3000/api/inmuebles/78